# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20160923_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='img/dashboard_template_image.png', upload_to='media/images/', verbose_name='img'),
        ),
    ]
