# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-06 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20161005_1935'),
        ('teams', '0004_auto_20161005_1242'),
    ]

    operations = [
    ]
