# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
