# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_invite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
