# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-11 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0009_auto_20161009_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(default=None, max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
