# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-12 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_organizationinvitation'),
        ('teams', '0010_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organization'),
        ),
    ]
