# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 20:04
from __future__ import unicode_literals

from django.db import migrations


def delete_orfan_teams(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    for team in Team.objects.filter(organization=None):
        print "Delete %s team" % (team.title,)
        team.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_team_organization'),
    ]

    operations = [
        migrations.RunPython(delete_orfan_teams),
    ]
