version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      # Update transitive dependencies too.
      - dependency-type: "all"
    versioning-strategy: increase-if-necessary
