# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('activityId', models.IntegerField()),
                ('expiredAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
