# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(default=b'img/dashboard_template_image.png', upload_to=b'media/images/', verbose_name=b'img'),
        ),
    ]
