# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(upload_to=b'media/images/', verbose_name=b'img'),
        ),
    ]
