# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-11 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161010_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=b'', max_length=255)),
                ('token', models.CharField(max_length=64)),
                ('expired', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
    ]
