# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=b''),
        ),
    ]
