# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
