# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 08:07
from __future__ import unicode_literals

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('app', 'Profile')

    for user in User.objects.all():
        if not hasattr(user, 'profile'):
            Profile(user=user).save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161013_1906'),
    ]

    operations = [
        migrations.RunPython(create_profiles)
    ]
