# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
