# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20160731_0323'),
        ('gigs', '0003_gig_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='team',
            field=models.ManyToManyField(to='people.Person'),
        ),
    ]
