# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_gig_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
