# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_auto_20160731_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
