# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_auto_20160802_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='admin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
