# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_auto_20160802_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='team',
            field=models.ManyToManyField(related_name='gig_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
