# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0010_auto_20160802_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='gig',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.Gig'),
        ),
        migrations.AddField(
            model_name='team',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.Role'),
        ),
    ]
