# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_remove_gig_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
