# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0014_auto_20160804_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='approved',
        ),
        migrations.AddField(
            model_name='team',
            name='approved',
            field=models.NullBooleanField(),
        ),
    ]
