# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=400)),
                ('photo_url', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
