# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_delete_personadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100)),
                ('organisation_url', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('members', models.ManyToManyField(to='people.Person')),
            ],
        ),
    ]
