# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-23 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20160723_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(),
        ),
    ]
