# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20160801_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile_pics/%Y/%m/%d'),
        ),
    ]
