# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20160801_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user',
            new_name='profile',
        ),
    ]
