# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20160802_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/profile_pics/%Y/%m/%d'),
        ),
    ]
