name: Unit Testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
jobs:
  run-unit-testing:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Python 3.9
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      # Run unit tests
      - name: Run unit tests with coverage
        run: pytest